spring:
  datasource:
    url: "jdbc:h2:file:./database/accountability;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH"
    username: accountability
    password: accountability-pw

logging:
  file:
    path: "./logs"
    name: "./logs/accountability.log"
  level:
    com.github.holly: INFO

