spring:
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterAccess=30m
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    show-sql: false
  threads:
    virtual:
      enabled: true
  mail:
    host: "smtp.gmail.com"
    port: ${ACCOUNTABILITY_EMAIL_PORT:587}
    username: "${ACCOUNTABILITY_EMAIL_ADDRESS:example@gmail.com}"
    password: "${ACCOUNTABILITY_EMAIL_PASSWORD:accountability-pw}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  datasource:
    url: "jdbc:h2:file:./database/accountability;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH"
    username: accountability
    password: accountability-pw
  h2:
    console:
      enabled: false

logging:
  file:
    path: "./logs"
    name: "./logs/accountability.log"
  logback:
    rollingpolicy:
      max-history: 14
      max-file-size: 100MB
      clean-history-on-start: true
  level:
    com.github.holly: INFO

application:
  base-url: "http://localhost:8080"

